### ISSUE TITLE
TODO: v2.2.0

### ISSUE THREAD

**Issue by maskatsum** [digital-go-jp/abr-geocoder#175]
- [ ]SQLを [Knex.js](https://knexjs.org/) に対応させる　→　複数のDBタイプに対応できるようになる

**Comment by maskatsum** [comment]
- [ ] 管理画面を作る（ダウンロードや更新チェックなどを管理画面からできるようにする）
- [ ] Docker compose で簡単に起動できるようにする
- [ ] `大字のみ`,`大字+地番`,`大字+住居表示`, `大字+地番+住居表示` の選択的ダウンロードができるようにする
- [ ] web画面を統合していく（docker compose で連携させる)

**Comment by koswatana** [comment]
- [ ] 地域を指定してダウンロード(Specify region(s) for download) のlg_code指定してダウンロードできるようにする
  - lg_code全部羅列は数が多いのでUIは要検討
- [ ] 現在のDB内の状況が確認できるようにする
  - 大字のみ,大字+地番,大字+住居表示, 大字+地番+住居表示のどの状況なのか、どのlg_codeのデータがあるのか

**Comment by koswatana** [comment]
ダウンロード対象を設定ファイル(yamlなど)で持てるようにしたい
